<?php
    session_start();
    unset($_SESSION['email']);
    unset($_SESSION['usertype']);
    session_destroy();
    $htmlpath='/project/';
    header('Location:'.$htmlpath.'index.php');
    die();
?>
